# Włączenie natywnego mechanizmu nadpisywania tabel ACPI w Dracut
acpi_override="yes"
acpi_table_dir="/etc/dracut.conf.d/acpi"

# Dodanie reguły udev wyłączającej dGPU do obrazu initramfs
install_items+=" /etc/udev/rules.d/99-nvidia-remove.rules "
